### ISSUE TITLE
haproxy was not installed?

### ISSUE THREAD

**Issue by hopewise** [cowops/debian-haproxy#1]
I tried your role, however, when I ssh to the instance, I get this:

```
$ haproxy -v
-bash: haproxy: command not found
```

Any idea?

Here is how I've used the role:
- name: Install HAProxy
  hosts: haproxy
  remote_user: admin
  sudo: yes
  roles:
  - role: cowops.debian-haproxy

**Comment by loranger** [comment]
haproxy should be installed as a service.

Does `sudo service haproxy status` returns something better ?

**Comment by loranger** [comment]
I suppose it does
